name: Replace Raw Content Links

on:
  push:
    branches:
      - main # 在 main 分支进行操作，必要时调整
  workflow_dispatch: # 允许手动触发

jobs:
  replace-urls:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find and replace URLs
        run: |
          # 定义目标目录
          TARGET_DIR="./"

          # 替换所有以 https://ghproxy.com/https://raw.githubusercontent.com/ 开头的链接
          find $TARGET_DIR -type f -name "*" -exec sed -i \
          's|https://ghproxy.com/https://raw.githubusercontent.com/|http://yubou.us.kg/https://raw.githubusercontent.com/|g' {} +

          # 替换所有以 https://mirror.ghproxy.com/https://raw.githubusercontent.com/ 开头的链接
          find $TARGET_DIR -type f -name "*" -exec sed -i \
          's|https://mirror.ghproxy.com/https://raw.githubusercontent.com/|http://yubou.us.kg/https://raw.githubusercontent.com/|g' {} +

          # 替换所有以 https://ghp.ci/https://raw.githubusercontent.com/ 开头的链接
          find $TARGET_DIR -type f -name "*" -exec sed -i \
          's|https://ghp.ci/https://raw.githubusercontent.com/|http://yubou.us.kg/https://raw.githubusercontent.com/|g' {} +

          # 替换所有没有加速前缀的 https://raw.githubusercontent.com/ 链接
          find $TARGET_DIR -type f -name "*" -exec sed -i \
          's|https://raw.githubusercontent.com/|http://yubou.us.kg/https://raw.githubusercontent.com/|g' {} +

      - name: Commit and push changes
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Replace all raw.githubusercontent.com URLs with new proxy" || echo "No changes to commit"
          git push https://$PAT_TOKEN@github.com/${{ github.repository }} HEAD:${{ github.ref_name }}
