name: Replace URLs in repository

on:
  push:
    branches:
      - main  # 可以根据需要指定其他分支

jobs:
  replace_urls:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up git config
    - name: Set up Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    # Replace URLs in all files
    - name: Replace all raw.githubusercontent.com URLs with new proxy
      run: |
        # Replace all occurrences of the old proxy URLs with the new one
        find . -type f -exec sed -i 's|https://ghproxy.com/https://raw.githubusercontent.com/|http://yubou.us.kg/raw.githubusercontent.com/|g' {} \;
        find . -type f -exec sed -i 's|https://mirror.ghproxy.com/https://raw.githubusercontent.com/|http://yubou.us.kg/raw.githubusercontent.com/|g' {} \;
        find . -type f -exec sed -i 's|https://ghp.ci/https://raw.githubusercontent.com/|http://yubou.us.kg/raw.githubusercontent.com/|g' {} \;
        find . -type f -exec sed -i 's|https://raw.githubusercontent.com/|http://yubou.us.kg/raw.githubusercontent.com/|g' {} \;

    # Commit and push the changes
    - name: Commit and push changes
      run: |
        git add .
        git commit -m "Replace all raw.githubusercontent.com URLs with new proxy"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # 使用 GitHub 内置的 token 进行推
