name: Replace URLs in Repository

on:
  push:
    branches:
      - main

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Replace URLs in files
      run: |
        find . -type f -name "*.txt" -o -name "*.md" -o -name "*.yml" \
        -exec sed -i 's#https://ghproxy.com/https://raw.githubusercontent.com/#http://yubou.us.kg/#g' {} \;
        find . -type f -name "*.txt" -o -name "*.md" -o -name "*.yml" \
        -exec sed -i 's#https://raw.githubusercontent.com/#http://yubou.us.kg/#g' {} \;

    - name: Configure Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit and push changes
      env:
        PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git add .
        git commit -m "Replace all raw.githubusercontent.com URLs with new proxy"
        git push "https://x-access-token:${PAT_TOKEN}@github.com/${{ github.repository }}.git" HEAD:${{ github.ref_name }}
