name: Fix Broken Links

on:
  workflow_dispatch: # 手动触发工作流
  push:              # 每次代码推送时触发
    paths:
      - '**/*.json'  # 仅在 JSON 文件更改时触发

jobs:
  fix_links:
    runs-on: ubuntu-latest

    steps:
    # 检出代码
    - name: Checkout repository
      uses: actions/checkout@v3

    # 查找并修复错误的链接
    - name: Fix links in JSON files
      run: |
        # 查找所有 .json 文件
        for file in $(find . -name "*.json"); do
          echo "Processing $file"
          # 替换错误的链接
          sed -i 's#http://yubou.us.kg/raw.githubusercontent.com/#https://raw.githubusercontent.com/#g' "$file"
          sed -i 's#https://yubou.us.kg/http://yubou.us.kg/raw.githubusercontent.com/#https://yubou.us.kg/https://raw.githubusercontent.com/#g' "$file"
        done

    # 提交并推送更改
    - name: Commit and push changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Fix broken links in JSON files"
        git push
